name: Upload Chrome extension

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build zip
        run: zip -r dist.zip dummy-extension

      - name: Upload Chrome Extension
        uses: pHo9UBenaA/chrome-extension-upload-action@master
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          extension-id: "jbebiebmbhiedoacjkgfkmdbgodefkjc"
          file-path: "./dist.zip"
          publish: "false"
